---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/cbrgm/tcplatency

steps:
  - name: build
    pull: always
    image: golang:1.11-alpine
    environment:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org
    commands:
      - apk add -U git make
      - make fmt
      - make test
      - make build
    when:
      event:
        - push
        - tag
        - pull_request

  - name: release
    pull: default
    image: golang:1.11-alpine
    environment:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org
    commands:
      - apk add -U git make
      - make release
    when:
      event:
        - tag

  - name: github
    pull: default
    image: plugins/github-release
    settings:
      files: "dist/*"
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event:
        - tag
